apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Backend Config
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-svc:3306/todolist"
  SPRING_DATASOURCE_USERNAME: "root"
  CORS_ALLOWED_ORIGINS: "http://192.168.80.129:32000"
  JWT_expirationMs: "36000000"
  # Frontend Config (브라우저에서 접근하므로 VM IP:NodePort 사용)
  VITE_API_URL: "http://192.168.80.129:32080"
  # DB Config
  MYSQL_DATABASE: "todolist"
  MYSQL_USER: "root"
