apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "todo-list-chart.fullname" . }}-frontend-ingress
  labels:
    {{- include "todo-list-chart.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: todo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "todo-list-chart.fullname" . }}-frontend-service
                port:
                  number: {{ .Values.frontend.service.port }}
