backend:
  replicaCount: 2
  image:
    repository: hwplus/k8s-labs-todo-backend
    tag: "2effa4f"  # 최신 CI 빌드 태그
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort:
      enabled: true
      port: 30001
  cors_allowed_origins: http://localhost:3000

database:
  name: tododb
  user: todouser
  password: "todo1234"
  rootPassword: "root1234"
